# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Fatin Idris's Portfolio # This is what shows up in the tab of the browser

# Hero Section
name: Norfatin Hazirah Mohd Idris
short_first_name: Fatin
headline: Fresh Mechanical Precision Engineer Graduate
description: >- # dont remove this line. this will ignore all new lines until the next section
  A mechanical engineering graduate passionate about innovation and technology.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.png


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive
resume-url: ./assets/resume/Resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: fatin-04-20    # https://www.linkedin.com/in/fatin-04-20/
  email: norfatinhazirahmohdidris@yahoo.com            # Replace with your actual email address
  github: remedyyyyyy    # https://github.com/{remedyyyyyy}
  stackoverflow:        # https://stackoverflow.com/users/{your url slug}
  medium:              # https://medium.com/@{your url slug}
  x-twitter:    # https://x.com/{your url slug}
  threads:              # https://threads.net/@{your url slug}
  instragram:        # https://instagram.com/{your url slug}
  youtube:              # https://youtube.com/@{your url slug}
  discord:              # https://discord.com/users/{your url slug}
  bluesky:              # https://bsky.app/profile/{your url slug}


# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise.
skills:
  - category: 3D Modeling
    tools:
    - AutoCAD
    - Autodesk Inventor
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)
    - Siemens NX
    - Inventor (Autodesk)
    - CATIA (Dassault Systèmes)
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - SLS
    - DMLS
    - PolyJet Printing
    - Vacuum Casting
    - Laser Cutting
    - Water Jet Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Design Standards / Practices
    tools:
    - GD&T ASME Y14
    - ISO fits and tolerances
    - PLM (PTC Windchill / Arena)
  - category: PCB Design
    tools:
    - Altium Designer
    - Altium
    - Eagle
    - KiCad
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA
    - Six Sigma methodologies
    - Shain Red-X

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key: https://formspree.io/f/mkgbzlqa


# Active theme (Update this to switch themes). Make sure to keep the indentation the samne.
colors: # Your new custom palette!
  text: "#374375"             # Main text color (pure black)
  border: "#effdff"           # Very light border color (light blue/cyan)
  link: "#7a8ad8"             # Link color (medium purple/blue)
  highlight: "#34d9fa"        # Highlight/accent color (very similar medium purple/blue)
  background: "#f8fce9"       # Main site background (very light warm white)
  light_background: "#e8d9ed" # Light background for sections/cards (pale yellow/greenish tint)


soothing blue-pastel theme (skills bg and skills text not great combo): 
  text: "#1A1A1A"             # Very dark grey, almost black, for main text (good on light background)
  border: "#E6E6E6"           # Light grey for subtle borders/dividers
  link: "#5D4FA8"             # Dark purple/blue for links
  highlight: "#99EEF2"        # Light cyan for highlights/accents
  background: "#FFFADE"       # <--- NOW THE CREAM/OFF-WHITE for the main site background
  light_background: "#5D4FA8" # <--- NOW THE DARK PURPLE/BLUE for alternating sections or secondary backgrounds

# A few examples.
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

Fresh & Modern Theme (almost the same as basic theme with a hint of green) :
  text: "#333d47"        # A soft charcoal, easy to read
  border: "#e0e7eb"      # A light, clean grey for subtle lines
  link: "#3478B2"        # A calming, professional blue
  highlight: "#2e7d32"    # A deep, subtle green for accents
  background: "#ffffff"  # Pure white for crispness
  light_background: "#f8f9fa" # A very subtle off-white, almost imperceptible but adds depth

Clean & Dynamic Theme (almost like basic with a hint of red)) :
  text: "#2c3e50"        # A strong, dark blue-grey for clear text
  border: "#d3dbe0"      # A cool, crisp light grey for borders
  link: "#2980b9"        # A bright, striking blue for links
  highlight: "#e74c3c"    # A vibrant, energetic red for highlights/attention
  background: "#ffffff"  # Pure white for a sharp contrast
  light_background: "#f6f8fa" # A very subtle cool off-white

Energetic & Playful Theme (Almost like basic, very clean with red pop and a hint of green):
  text: "#212121"        # A strong, almost black for excellent readability
  border: "#ECEFF1"      # A very light, crisp grey for clean lines
  link: "#FF5722"        # A bold, vibrant orange for links that pop!
  highlight: "#4CAF50"    # A fresh, bright green for accents
  background: "#ffffff"  # Pure white for maximum contrast
  light_background: "#F5F5F5" # A subtle, light grey for section breaks

Palette 2 Deep Ocean & Mist ( very basic, no other hint) :
  text: "#2f4156"          # The darkest blue-grey for main text, excellent readability
  border: "#8c8d8b"        # A subtle medium grey for defining borders
  link: "#567c8d"          # The medium blue-grey for links, visible yet harmonious
  highlight: "#567c8d"    # Reusing the medium blue-grey for a calm highlight
  background: "#ffffff"    # Pure white for a crisp primary background
  light_background: "#f0f0f0" # The very light grey for alternating sections, subtle contrast

  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

  XPastel Dream Theme (Similar to Mint, very pastel-y but the combo ;link isnt great) :
  text: "#5E6C7D"        # A muted, deep blue-grey for readability
  border: "#D3DBE2"      # A very light, soft grey-blue for subtle dividers
  link: "#A8DADC"        # A gentle, soft teal for links
  highlight: "#B9E1DD"    # A slightly lighter, minty highlight
  background: "#F2F7FA"  # A very light, almost white, cool background
  light_background: "#E8EFF4" # A slightly deeper, soft blue-grey for sections

lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"

Palette 8 Gentle Lavender & Sky (Pastel!, Cream BG with accent of blue and purple) :
  text: "#0b1957"          # The very dark navy for strong, readable text
  border: "#e9f1ff"        # The very light pastel blue for ultra-soft borders.
  link: "#625d8c"          # The medium lavender-blue for gentle, clickable links.
  highlight: "#d2b3db"    # The soft pastel purple for a lovely, subtle highlight.
  background: "#f7f4ed"    # The soft off-white/cream for the main background.
  light_background: "#e9f1ff" # The very light pastel blue for alternating sections, super soft.

  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

Palette 10 Bold Contrast & Energy (Red-based/ muted red) :
  text: "#2b124c"          # The dark purple-blue for strong, readable text.
  border: "#fbe4d8"        # The very light peach for soft, contrasting borders.
  link: "#8c414c"          # The dark muted red for rich links.
  highlight: "#ff002c"    # The bright, pure red for an incredibly vibrant highlight!
  background: "#fbe4d8"    # The very light peach for the main background.
  light_background: "#ffffff" # Pure white for alternating sections, sharp contrast.

Warm & Inviting Theme :
  text: "#4F4A45"        # A warm, deep brown-grey for excellent readability.
  border: "#EAD7C2"      # A soft, light beige-brown for gentle separations.
  link: "#7F553B"        # A rich, inviting terra-cotta/brown link color.
  highlight: "#A1826A"    # A slightly lighter, warm brown for highlights.
  background: "#FBF8F3"  # A very soft, warm off-white background.
  light_background: "#F5F0EC" # A slightly deeper warm off-white for sections.

Palette 3 Urban Chic & Warm Neutrals (similar to warm, with white background) :
  text: "#000000"          # Classic black for maximum text contrast.
  border: "#b7a7a2"        # The muted rose/taupe for soft, natural borders.
  link: "#91766e"          # The warm dark brown/taupe for prominent links.
  highlight: "#91766e"    # Reusing the warm dark brown/taupe for highlights.
  background: "#ffffff"    # Pure white for the main background.
  light_background: "#f0ece3" # The light warm beige for subtle alternating sections.

Palette 2 Cool Breeze & Mountain Peaks (White BG with Nude accent and a hint of blue):
  text: "#2f4156"          # The dark blue-grey ensures excellent readability for all your text.
  border: "#c8d9e6"        # The light, cool blue-grey creates very soft and clean border lines.
  link: "#567c8d"          # Your medium cool blue-grey makes for distinct yet harmonious links.
  highlight: "#567c8d"    # Reusing the medium blue-grey provides a consistent, calming highlight for interactions.
  background: "#ffffff"    # A crisp pure white for your primary background, offering maximum clarity.
  light_background: "#f5efeb" # The very light, warm off-white gives a subtle, inviting shift for sections.

Palette 3 Modern Contrast & Earthy Comfort (very similar to above):
  text: "#000000"          # Strong black text for ultimate readability and a bold statement.
  border: "#b7a7a9"        # The muted dusty rose/taupe makes for gentle, sophisticated separators.
  link: "#91766e"          # Your warm, rich brown is a lovely, inviting color for links.
  highlight: "#91766e"    # Using the same warm brown for highlights keeps the theme cohesive and elegant.
  background: "#ffffff"    # Pure white for a clean, bright main background.
  light_background: "#f6ece3" # The light warm beige for subtle shifts between sections, adding warmth.

Palette 5 Vintage Serenity (Nice warm brownish tone):
  text: "#223030"          # The very dark grey-green offers strong, natural-feeling text contrast.
  border: "#959d90"        # The muted green-grey creates subtle, harmonious borders.
  link: "#523d35"          # The dark, desaturated brown for links that feel grounded and distinct.
  highlight: "#bba58f"    # Your soft, warm beige/greige works as a gentle, inviting highlight.
  background: "#efefe9"    # The very light, off-white for a serene main background.
  light_background: "#e8d9cd" # The light, dusty rose/cream provides a soft, warm shift for sections.

Palette 9 Vibrant Punch & Calm Bases (kinda digging this! cream BG with blue and brown accent) :
  text: "#374375"          # The dark, muted blue-purple provides strong, elegant text.
  border: "#babde2"        # The light, muted lavender-blue for soft, clean borders.
  link: "#895159"          # Your dark, muted berry red makes for distinct and inviting links.
  highlight: "#ba4020"    # The light, soft peach for a warm, gentle highlight.
  background: "#fffcf5"    # The almost pure white for a crisp, bright main background.
  light_background: "#cdd0f7" # The light, muted lavender-blue for alternating sections, adding a touch of calm.

Palette 8 Dreamy Lavender Sunset (Pastel! Cream BG, with purple accent and blue) :
  text: "#0b1957"          # The very dark navy ensures excellent readability on light pastel backgrounds.
  border: "#e9f3ff"        # The very light, pale blue for incredibly soft, barely-there borders.
  link: "#426bc2"          # Your vibrant mid-tone blue makes for clear and engaging links.
  highlight: "#e8d9ed"    # The light pastel lavender for alternating sections, adding gentle depth.
  background: "#f7f4ed"    # The light off-white/cream for your calming main background.
  light_background: "#d2b3db" # The soft pastel purple provides a delicate yet noticeable highlight.


  custom1 theme:
  text: "#545454"
  border: "#f1ece5"
  link: "#bd9e89"
  highlight: "#bd9e89"
  background: "#faede0"
  light_background: "#e4c982"


#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
