# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Fatin Idris's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Fatin Idris
headline: Fresh Mechanical Precision Engineer Graduate
description:  >- # dont remove this line. this will ignore all new lines until the next section
  A mechanical engineering graduate passionate about innovation and technology.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.png


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: ./assets/resume/Resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: fatin-04-20    # https://www.linkedin.com/in/fatin-04-20/ 
  email: norfatinhazirahmohdidris@yahoo.com          # Replace with your actual email address
  github: remedyyyyyy    # https://github.com/{remedyyyyyy} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - AutoCAD
    - Autodesk Inventor
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)
    - Siemens NX
    - Inventor (Autodesk)
    - CATIA (Dassault Systèmes)
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - SLS
    - DMLS
    - PolyJet Printing
    - Vacuum Casting
    - Laser Cutting
    - Water Jet Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Design Standards / Practices
    tools:
    - GD&T ASME Y14
    - ISO fits and tolerances
    - PLM (PTC Windchill / Arena)   
  - category: PCB Design
    tools:
    - Altium Designer
    - Altium
    - Eagle 
    - KiCad
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Six Sigma methodologies
    - Shain Red-X

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/mkgbzlqa



# Active theme (Update this to switch themes). Make sure to keep the indentation the samne.
colors: # Warm & Inviting Theme
  text: "#4F4A45"        # A warm, deep brown-grey for excellent readability
  border: "#EAD7C2"      # A soft, light beige-brown for gentle separations
  link: "#7F553B"        # A rich, inviting terra-cotta/brown link color
  highlight: "#A1826A"   # A slightly lighter, warm brown for highlights
  background: "#FBF8F3"  # A very soft, warm off-white background
  light_background: "#F5F0EC" # A slightly deeper warm off-white for sections
  
# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
Fresh & Modern Theme (almost the same as basic theme) :
  text: "#333d47"        # A soft charcoal, easy to read
  border: "#e0e7eb"      # A light, clean grey for subtle lines
  link: "#3478B2"        # A calming, professional blue
  highlight: "#2e7d32"   # A deep, subtle green for accents
  background: "#ffffff"  # Pure white for crispness
  light_background: "#f8f9fa" # A very subtle off-white, almost imperceptible but adds depth

Clean & Dynamic Theme (almost like basic with a hint of red)) :
  text: "#2c3e50"        # A strong, dark blue-grey for clear text
  border: "#d3dbe0"      # A cool, crisp light grey for borders
  link: "#2980b9"        # A bright, striking blue for links
  highlight: "#e74c3c"   # A vibrant, energetic red for highlights/attention
  background: "#ffffff"  # Pure white for a sharp contrast
  light_background: "#f6f8fa" # A very subtle cool off-white
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

  XPastel Dream Theme (Similar to Mint, very pastel-y but the combo ;link isnt great) : 
  text: "#5E6C7D"        # A muted, deep blue-grey for readability
  border: "#D3DBE2"      # A very light, soft grey-blue for subtle dividers
  link: "#A8DADC"        # A gentle, soft teal for links
  highlight: "#B9E1DD"   # A slightly lighter, minty highlight
  background: "#F2F7FA"  # A very light, almost white, cool background
  light_background: "#E8EFF4" # A slightly deeper, soft blue-grey for sections

Warm & Inviting Theme (Almost same as Mint/Greenish) :
  text: "#4F4A45"        # A warm, deep brown-grey for excellent readability
  border: "#EAD7C2"      # A soft, light beige-brown for gentle separations
  link: "#7F553B"        # A rich, inviting terra-cotta/brown link color
  highlight: "#A1826A"   # A slightly lighter, warm brown for highlights
  background: "#FBF8F3"  # A very soft, warm off-white background
  light_background: "#F5F0EC" # A slightly deeper warm off-white for sections
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"

  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

Energetic & Playful Theme (Almost like basic, very clean with red pop and a hint of green): 
  text: "#212121"        # A strong, almost black for excellent readability
  border: "#ECEFF1"      # A very light, crisp grey for clean lines
  link: "#FF5722"        # A bold, vibrant orange for links that pop!
  highlight: "#4CAF50"   # A fresh, bright green for accents
  background: "#ffffff"  # Pure white for maximum contrast
  light_background: "#F5F5F5" # A subtle, light grey for section breaks

  custom1 theme:
  text: "#545454"
  border: "#f1ece5"
  link: "#bd9e89"
  highlight: "#bd9e89"
  background: "#faede0"
  light_background: "#e4c982"
  





#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
